force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ATM_Fee_in_other_currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_other_currencies__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ATM Fee in other currencies</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cost per Calendar Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

.history/force-app/main/default/classes/TestSetup_20200810030858.cls
/**
 * @description       : 
 * @author            : shafaqbashir
 * @group             : 
 * @last modified on  : 08-10-2020
 * @last modified by  : shafaqbashir
 * Modifications Log 
 * Ver   Date         Author         Modification
 * 1.0   08-10-2020   shafaqbashir   Initial Version
**/

public class TestSetup {
  public static void setupCustomerProductInformation() {
    ID standardPBID = Test.getStandardPricebookId();
    Pricebook2  priceBook = new Pricebook2 (Name = 'DE', isActive=true);	
    insert priceBook;
    Product2 myProduct = new Product2(Name = 'Test', ProductCode = 'Test', Family = 'Test', IsActive = true);
    insert myProduct;
    PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = standardPBID, Product2Id = myProduct.Id, UnitPrice = 100, IsActive = true,  currencyISOCode = 'EUR');
    insert standardPrice;
    PricebookEntry pricebe = new PricebookEntry(Pricebook2Id = priceBook.Id, Product2Id = myProduct.Id, UnitPrice = 150, IsActive = true, ATM_Fee_in_other_currencies__c = 0.01, Card_Replacement_Cost__c = 5,Cost_per_Calendar_Month__c = 6, CurrencyIsoCode = 'EUR' );
    insert pricebe;
    Account acc = new Account(Name = 'Test Account');
    insert acc;
    Contact con = new Contact(FirstName = 'John', LastName = 'Doe', AccountId = acc.Id, UUID__c = '2345', Product__c = myProduct.Id, Home_Country__c = 'DE');
    insert con;
    Case c = new Case(ContactId = con.Id);
    insert c;    
  }

}