force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ATM_Fee_in_other_currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_other_currencies__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ATM Fee in other currencies</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cost per Calendar Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

.history/force-app/main/default/classes/ContactProductQueryServices_20200810022359.cls
/**
 * @description       : 
 * @author            : shafaqbashir
 * @group             : 
 * @last modified on  : 08-10-2020
 * @last modified by  : shafaqbashir
 * Modifications Log 
 * Ver   Date         Author         Modification
 * 1.0   08-10-2020   shafaqbashir   Initial Version
**/

public class ContactProductQueryServices {
  public static Id getProductEntry(String productId, String homeCountry) {

    return [SELECT Id, Product2.Name, ATM_Fee_in_other_currencies__c, Card_Replacement_Cost__c, Cost_per_Calendar_Month__c, Pricebook2.Name, CurrencyIsoCode FROM PricebookEntry WHERE Pricebook2.Name  = : homeCountry AND Product2Id = : productId LIMIT 1].Id;
  }

  public static List<PricebookEntry> getProductEntries(Set<Id> productList, Set<String> homeCountryList) {

    return [SELECT Id, Product2Id, Product2.Name, ATM_Fee_in_other_currencies__c, Card_Replacement_Cost__c, Cost_per_Calendar_Month__c, Pricebook2.Name, CurrencyIsoCode FROM PricebookEntry WHERE Pricebook2.Name  In : homeCountryList AND Product2Id In : productList];
  }
  public static List<Contact> getContacts(Set<String> uuidList) {

    return [SELECT Id, Product__c, UUID__c, Home_Country__c FROM Contact WHERE UUID__c IN :uuidList];
  }

}